### ISSUE TITLE
Color.lerp inconsistent with Vec2.lerp

### ISSUE THREAD

**Issue by szymonkaliski** [pex-gl/pex-color#10]
In `pex-geom` we have `Vec2.lerp(v, k)`, but with `pex-color` we have different api: `Color.lerp(c1, c2, k)`.

**Comment by vorg** [comment]
Rationale is that colors usually come with color palettes so you don't want to modify them. But I agree I would be good to add instance method so 

```
Color.lerp(Color.Red, Color.Green, 0.5)
```

Would become

```
Color.Red.clone().lerp(Color.Green, 0.5)
```

**Comment by vorg** [comment]
What about renaming it to mix to avoid confusion and keeping lerp the Vec3 way.

**Comment by szymonkaliski** [comment]
yeah sounds good 👍

**Comment by vorg** [comment]
Spring cleaning in progress!!!

**Comment by dmnsgn** [comment]
Not applicable anymore
