### ISSUE TITLE
Add support for HSLUV and other color spaces

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-color#17]
https://www.npmjs.com/package/hsluv

**Comment by vorg** [comment]
As this is major version i wouldn't be afraid of killing color spaces either. Yes HSL is classic but you should almost always use HSLuv these days (or OKLab).

**Comment by vorg** [comment]
| Colorspace  | Data    | Notes |
| ----------- | ----- | ------ |
| RGB 0-255 | [r, g, b]      | sRGB bytes e.g. from HTML Canvas      |
| RGB 0-1   | [r,g,b,a] | sRGB float        |
| Linear RGB | [r, g, b, a] | eventually all shaders should use linear colors so conversion utils would be handy|

...

**Comment by dmnsgn** [comment]
RGB, HSL and Hex are still what you get in your browser's color picker though.
I don't see any harm in having these methods here so I wouldn't kill them entirely but maybe just un-document them.

**Comment by vorg** [comment]
i do wonder if it would be dangerous to assume `[255, 255, 255, 255]` = sRGB and `[1, 1, 1, 1]` = linear RGB

**Comment by vorg** [comment]
Although probably not possible as e.g. HSLuv converts from linear back to sRGB in the last step of algo, but you get 0..1 values.
