### ISSUE TITLE
lerp(a, b, t) is missing

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-color#20]
v1 had color.lerp that is not present in v2

**Comment by dmnsgn** [comment]
I think we agreed to remove this utility as we have vec3/4 lerp in pex-math.
If we want it back, are there any other useful utils (such as distance, difference, blend..)

**Comment by vorg** [comment]
I just found myself in non webgl project that didn’t use pex-math but needed to make colour gradient based on data value and usual approach would be to use d3-scale-chromatic but sometimes you just want simple HSLuv. I’ve never used any of the mentioned functions in the last 3y so i think we are ok without them.

Speaking of utilis (same about math). Is it useful to have it namespaces when importing? 

Isn’t this preferred:

```js
import { toLinear } from “pex-color”
```

**Comment by dmnsgn** [comment]
Actually even in v1, lerp was commented.
