### ISSUE TITLE
What does toRGB do?

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-color#21]

**Comment by dmnsgn** [comment]
`Returns a copy of a RGB color` optionally setting it to the provided color via out parameter (`toRGB([r, g, b, a], out = [])`. Matches the other `fromColorSpace/toColorSpace` methods.


```js
// rgb.js:
const myColor = color.create(0, 1, 0, 1);

// Actually I want random red
const r = 1;
const g = Math.random() * 0.1;
const b = Math.random() * 0.1;

// Let me set it from RGB color space values:
color.fromRGB(myColor, r, g, b);

const myColorCopyToUseSomewhereElse = color.create();
color.toRGB(myColor, myColorCopyToUseSomewhereElse);

// color.js (same as pex-math style):
// copy the array
const deepCopy = color.copy(myColor);
// => equivalent to color.toRGB(myColor);

// Set it to blue
const myBlueColor = color.create(0, 0, 1, 1);
color.set(deepCopy, myBlueColor);
// => different function signature from color.fromRGB(color, r, g, b, a) (number arguments)
// => an array color.set(color, color2) (array argument)
```

We could:
- either remove color.copy, to re-enforce the to/from logic even from a rgb color to a rgb color
- or remove toRGB (as equivalent to color.set()) and rename color.fromRGB to color.fromValues(color, r, g, b, a)

**Comment by vorg** [comment]
Option b) remove toRGB and rename fromRGB to fromValues

**Comment by vorg** [comment]
@dmnsgn how do we deal with it in context of minor release? Same deprecation mechanism as https://github.com/pex-gl/pex-color/issues/22 ?

**Comment by vorg** [comment]
Let's add `console.error` deprecation here too
