### ISSUE TITLE
toRGBBytes returns 4 numbers instead of 3

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-color#22]
This function is called RGB not RGBA bytes. We used to have distinction https://github.com/pex-gl/pex-color/issues/8. It currently breaks code like this by returning alpha as 255.

```js
ctx2d.fillStyle = `rgba(${toRGBBytes(bgColor).join(",")}, 1)`;
```

I think we should add toRGBABytes for clarity?

**Comment by dmnsgn** [comment]
Assuming bgColor is vec4 in your case.
All `toColorSpace` methods work by transforming the input array.
Here you should really use `ctx2d.fillStyle = toCSSRGB(bgColor)` (or `bgColor.slice(0, 3)` but what you want is a string for fillStyle).

**Comment by vorg** [comment]
But the i propose to remove it and rename to RGBABytes or toBytes. pex-color colors should always be RGBA.

Another inconsistency is toHex([1,0,0,1]) returns #FF0000 not #FF0000FF.

**Comment by dmnsgn** [comment]
> Then i propose to remove it and rename to RGBABytes or toBytes. pex-color colors should always be RGBA.
> 
> Another inconsistency is toHex([1,0,0,1]) returns #FF0000 not #FF0000FF.

`hex` space is special yes. Last time we discussed alpha for it, we settled on the fact it shouldn't be the default to return alpha but should still be possible. So currently you have to pass the second parameter toHex([1,0,0,1], true) to get all an #RRGGBBAA string. (and another improvement we have in v2 is support for RGB[A] or RRGGBB[AA] input for `fromHex` keeping the current alpha). 

`toBytes` makes sense to me.

**Comment by vorg** [comment]
> toBytes makes sense to me.

Could we remove toRGBBytes from api/docs and throw or log deprecated without doing major version bump?

**Comment by dmnsgn** [comment]
> > toBytes makes sense to me.
> 
> Could we remove toRGBBytes from api/docs and throw or log deprecated without doing major version bump?

yes

**Comment by vorg** [comment]
`console.error` then
